### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Zumbalamambo** [yupidevs/yupi#1]
Great workl! Please add some working examples

**Comment by gvieralopez** [comment]
Dear @Zumbalamambo. Thank you for your feedback. We are working hard to make the first release of yupi as stable as we can. At the moment, it is on alpha and some of the current API is changing from patch patch as we realize better ways to improve it. This fact has delayed us to provide some working examples just now.

However, later this week we should have the first examples ready (and hosted together with required multimedia files) at this repo:
https://github.com/yupidevs/yupi_examples

Additionally, we will provide some description of the examples in this section of the docs:
https://yupi.readthedocs.io/en/latest/examples/examples.html

We will keep this issue open until the first examples are ready, so you can get a notification when we release them.

**Comment by gvieralopez** [comment]
We already have 5 examples of usage of the library. All available at:

https://github.com/yupidevs/yupi_examples

Additionally, we will provide some description of the examples in this section of the docs:
https://yupi.readthedocs.io/en/latest/examples/examples.html

I am closing the issue now. Thanks again to @Zumbalamambo for the feedback.
